name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      
      - name: Add DigitalOcean to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy to DigitalOcean
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DEPLOY_PATH: /var/www/randomwordgenerator.info
        run: |
          # First sync all files except public/ and hapax-finder/ to the root deploy path
          rsync -avz --delete \
            --exclude=".git" \
            ./ root@$DROPLET_IP:$DEPLOY_PATH
      
          # SSH into the server for post-deployment tasks
          ssh root@$DROPLET_IP "\
            # Remove existing public_html if it's not a symlink
            if [ -d $DEPLOY_PATH/public_html ] && [ ! -L $DEPLOY_PATH/public_html ]; then
              rm -rf $DEPLOY_PATH/public_html
            fi

            # Re-create the symlink from public_html to public
            ln -sf $DEPLOY_PATH/public $DEPLOY_PATH/public_html
            
            # Install dependencies using Composer
            if [ -f $DEPLOY_PATH/composer.json ]; then
              cd $DEPLOY_PATH
              composer install --no-interaction --no-dev --optimize-autoloader
            fi
      
            # Set permissions and reload the server
            chown -R www-data:www-data $DEPLOY_PATH && \
            chmod -R 755 $DEPLOY_PATH && \
            systemctl reload apache2"
